# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/1603291b-d1ce-4107-9be0-4fc8348055fc";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  fileSystems."/.snapshots" =
    { device = "/dev/disk/by-uuid/1603291b-d1ce-4107-9be0-4fc8348055fc";
      fsType = "btrfs";
      options = [ "subvol=@snapshots" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/12CE-A600";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/1603291b-d1ce-4107-9be0-4fc8348055fc";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/1603291b-d1ce-4107-9be0-4fc8348055fc";
      fsType = "btrfs";
      options = [ "subvol=@nix" ];
    };

  fileSystems."/var/lib/docker" =
    { device = "/dev/disk/by-uuid/1603291b-d1ce-4107-9be0-4fc8348055fc";
      fsType = "btrfs";
      options = [ "subvol=@docker" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/1603291b-d1ce-4107-9be0-4fc8348055fc";
      fsType = "btrfs";
      options = [ "subvol=@log" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/928cde32-0784-46f3-9d35-59366166544e"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
