keys:
  - &users:
    - &ta age1csagu4v8k6nsk0zc7k6vtl27fzt54xtx6wc9makd4mhvgl9sauzqxk79t3
  - &hosts:
    - &athena age1cvyzp4ks8ymctc7gpelrfmg9wnpj9mv2cupw54wpvnanlvs9vqsqvjcqkz
    - &ares age1u7kvv7y0szr9f4cvyasjfyy2uhrdewuw4chner7f9axx8q34eetsn6vqny

creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
    - age:
      - *ta
      - *athena
      - *ares
